### PR TITLE
WhizzML update v0.16.1

### PR DESCRIPTION
**Pull request by osroca**
once it is merged it should be tagged as v0.1.1 (or the version number you prefer  but following the major-minor-micro)

(Please note that the gif added to README won't show until it is merged in master, the URL of the image has to be absolute to the github's raw server)

### CODE REVIEW

**Comment by jaor** [comment]
@osroca looks good, merged. should we add a tag? 0.16.1?

**Comment by osroca** [comment]
the tag is needed in order control package finds the new version atomatically and installs it in sublime. Do you want to tag it with the same version number as whizzml? I'm fine but looks a big jump to me, we have now v.0.1.0.

**Comment by jaor** [comment]
i just thought it might make easier to track what version the plugin
supports, but i guess we could have more than one release for the same
supported whizzml version. 0.1.1? 0.2.0?

**Comment by osroca** [comment]
yes, multiversion is supported, but the idea behind it is to develop packages for  different versions of sublime or different platforms. In the package definition (in packagecentral.io) one defines a mapping for that purpose, I don't know if it would work.

**Comment by osroca** [comment]
0.1.1? it only adds a couple of new primitives ...

**Comment by jaor** [comment]
0.1.1 sounds good to me. tagged!

**Pull request merged**
